" autocomandes
augroup programmation
	autocmd!
	autocmd FileType markdown call Markdown()
	autocmd FileType tex call Latex()
	autocmd FileType javascript call Javascript()
	autocmd FileType java call Java()
	autocmd FileType rust call Rust()
	autocmd FileType json call Json()
	autocmd	FileType r call RLike()
	autocmd BufRead,BufNewFile *.v call Coq()
	autocmd BufRead,BufNewFile *.cs call CSharp()
	autocmd BufRead,BufNewFile *.hs call Haskell()
	autocmd BufRead,BufNewFile *.nim call Nim()
	autocmd BufRead,BufNewFile *.mojo call Mojo()
	autocmd BufRead,BufNewFile *.tt call TypeTaking()
	autocmd FileType sh call Sh()
	autocmd FileType plantuml call Puml()
	autocmd BufRead,BufNewFile *.nu call Nu()
	autocmd FileType toml call Toml()
	autocmd BufRead,BufNewFile *.coco call Coconut()
	autocmd BufRead,BufNewFile *.qmd call Quarto()
	autocmd BufRead,BufNewFile *.typ call Typst()
	autocmd BufRead,BufNewFile grammar.js call TreeSitterClient()
augroup END
